name: Check Markdown documents

on:
  pull_request:
    paths:
      - '**.md'

jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint Markdown sources
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          config: '.markdownlint.json'
          args: './'

  check-urls:
    name: Check URLs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: urls-checker
        uses: urlstechie/urlchecker-action@0.0.27
        with:
          file_types: .md
          print_all: false
          exclude_patterns: localhost
